var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { baseStyles, disabledStyles, colors } from '../../styles';
export var StyledRadioButtonWrapper = styled.label(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  ", "\n  display: flex;\n  align-items: center;\n  user-select: none;\n  font-size: 95%;\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n"], ["\n  ", "\n  display: flex;\n  align-items: center;\n  user-select: none;\n  font-size: 95%;\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n"])), baseStyles);
export var StyledRadioButton = styled.span(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: relative;\n  height: 0.8rem;\n  width: 0.8rem;\n  border: 0.063rem solid ", ";\n  border-radius: 50%;\n  -webkit-border-radius: 50%;\n  -moz-border-radius: 50%;\n  -ms-border-radius: 50%;\n  -o-border-radius: 50%;\n  cursor: pointer;\n  margin-right: 0.625rem;\n  margin-left: 0.125rem;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n\n  :hover {\n    opacity: 0.75;\n  }\n\n  :after {\n    content: '';\n    height: 0;\n    width: 0;\n    background-color: ", ";\n    border-radius: 50%;\n    -webkit-border-radius: 50%;\n    -moz-border-radius: 50%;\n    -ms-border-radius: 50%;\n    -o-border-radius: 50%;\n    transition: all 0.3s ease-in-out;\n    -webkit-transition: all 0.3s ease-in-out;\n    -moz-transition: all 0.3s ease-in-out;\n    -ms-transition: all 0.3s ease-in-out;\n    -o-transition: all 0.3s ease-in-out;\n  }\n\n  ", "\n"], ["\n  position: relative;\n  height: 0.8rem;\n  width: 0.8rem;\n  border: 0.063rem solid ", ";\n  border-radius: 50%;\n  -webkit-border-radius: 50%;\n  -moz-border-radius: 50%;\n  -ms-border-radius: 50%;\n  -o-border-radius: 50%;\n  cursor: pointer;\n  margin-right: 0.625rem;\n  margin-left: 0.125rem;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n\n  :hover {\n    opacity: 0.75;\n  }\n\n  :after {\n    content: '';\n    height: 0;\n    width: 0;\n    background-color: ", ";\n    border-radius: 50%;\n    -webkit-border-radius: 50%;\n    -moz-border-radius: 50%;\n    -ms-border-radius: 50%;\n    -o-border-radius: 50%;\n    transition: all 0.3s ease-in-out;\n    -webkit-transition: all 0.3s ease-in-out;\n    -moz-transition: all 0.3s ease-in-out;\n    -ms-transition: all 0.3s ease-in-out;\n    -o-transition: all 0.3s ease-in-out;\n  }\n\n  ", "\n"])), colors.highlight, colors.highlight, function (_a) {
    var disabled = _a.disabled;
    return disabled && "" + disabledStyles;
});
export var StyledRadioButtonInput = styled.input(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: absolute;\n  opacity: 0;\n  z-index: -1;\n\n  :checked + ", ":after {\n    width: 0.5rem;\n    height: 0.5rem;\n  }\n\n  :focus-visible + ", " {\n    outline: 0.125rem solid ", ";\n  }\n\n  :focus:not(:focus-visible) + ", " {\n    outline: none;\n  }\n"], ["\n  position: absolute;\n  opacity: 0;\n  z-index: -1;\n\n  :checked + ", ":after {\n    width: 0.5rem;\n    height: 0.5rem;\n  }\n\n  :focus-visible + ", " {\n    outline: 0.125rem solid ", ";\n  }\n\n  :focus:not(:focus-visible) + ", " {\n    outline: none;\n  }\n"])), StyledRadioButton, StyledRadioButton, colors.highlight, StyledRadioButton);
var templateObject_1, templateObject_2, templateObject_3;
